version: '3'
services:
  app:
    build:
      context: . # The 'app' service is defined to build from the correct directory
      dockerfile: Dockerfile # The Docker Compose will use multi-stage Dockerfile to build the image
    # The 'Ports' and 'environment' directives make sure that the Flask app is accessible & correctly configured
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

